name: Rebuild

on:
  workflow_dispatch:

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      LARAVEL_VERSION: ${{ steps.fetch-laravel.outputs.version }}
      CURRENT_TAGS: ${{ steps.fetch-docker.outputs.tags }}
    steps:
      - name: Fetch the latest Laravel version
        id: fetch-laravel
        run: |
          curl -sL https://api.github.com/repos/laravel/laravel/releases/latest | jq -r ".tag_name" > .version
          echo "::set-output name=version::$(cat .version | awk '{print substr($0, 2)}')"
      
      - name: Fetch existing containers
        id: fetch-docker
        run: |
          ARRAY=$(curl -sL https://registry.hub.docker.com/v1/repositories/anterisdev/laravel-swoole/tags | jq -r '[ .[] | select(.name != "latest") | .name ]')
          echo "::set-output name=tags::"$ARRAY""

  rebuild-containers:
    runs-on: ubuntu-latest
    needs: fetch-versions
    strategy:
      fail-fast: false
      matrix:
        TAG: ${{ fromJson(needs.fetch-versions.outputs.CURRENT_TAGS) }}
    
    name: Build ${{ matrix.TAG }}

    steps:
      - name: Set Laravel install version
        run: |
          echo "LARAVEL_INSTALL_VERSION=$([ $(echo ${{ matrix.TAG }} | awk '{print length}') -eq 1 ] && echo "${{ matrix.TAG}}.*" || echo ${{ matrix.TAG }})" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        name: Check out code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Determine Docker Tags
        id: docker-tags
        run: echo "::set-output name=tags::$(echo $([ "${{ matrix.TAG }}" == "${{ needs.fetch-versions.outputs.LARAVEL_VERSION }}" ] && echo "anterisdev/laravel-swoole:latest,")anterisdev/laravel-swoole:${{ matrix.TAG }})"

      - name: Test Docker Tags
        run: echo "${{ steps.docker-tags.tags }}"

      - name: Build and push to Docker registry
        id: docker-build
        if: ${{ needs.fetch-versions.outputs.LARAVEL_VERSION != matrix.TAG }}
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: "LARAVEL_VERSION=${{ env.LARAVEL_INSTALL_VERSION }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          tags: ${{ steps.docker-tags.tags }}

      - name: Image digest
        if: steps.docker_build.conclusion == 'success'
        run: echo ${{ steps.docker-build.outputs.digest }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.docker-build.conclusion == 'success'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
